### ISSUE TITLE
webpackChunkNames are not applied/used, instead chunks are called "0.js", "1.js" and so on

### ISSUE THREAD

**Issue by natterstefan** [acrazing/typescript-loadable-components-plugin#3] opened 2020-08-29 18:43 UTC
Hi @acrazing,

first of all, thank you very much for your work. It works like a charm, except for one thing.

## The Problem

When I use this plugin with `babel-loader` and `ts-loader`, `webpackChunkName` does not work and chunks are just called `0.js`, `1.js` and so on. Here is a link to the [App.tsx](https://github.com/natterstefan/loadable-components-example/blob/8aa33e6441b54724df7c2836f10a8fa4fea12e2c/src/client/app.tsx#L10-L11), [babel-](https://github.com/natterstefan/loadable-components-example/blob/8aa33e6441b54724df7c2836f10a8fa4fea12e2c/babel.config.js) and [tsconfig](https://github.com/natterstefan/loadable-components-example/blob/8aa33e6441b54724df7c2836f10a8fa4fea12e2c/tsconfig.json).

```ts
// app.tsx
const Home = loadable(() => import('./pages/home'))
const About = loadable(() => import('./pages/about'))
```

```js
// wepack.config.js
 module: {
    rules: [
      {
        test: /\.(ts)x?$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'ts-loader',
            options: {
              getCustomTransformers: (program) => ({
                before: [createLoadableComponentsTransformer(program, {})],
              }),
            },
          },
        ],
      },
    ],
  },
```

```js
// babel.config.js
module.exports = {
  presets: [
    '@babel/preset-env',
    '@babel/preset-react',
    '@babel/preset-typescript',
  ],
  plugins: [
    '@loadable/babel-plugin',
  ],
}
```

```
// tsconfig.json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "esnext",
    "jsx": "react",
    "sourceMap": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true
  },
  "include": ["src/**/*"]
}
```

results in:

![image](https://user-images.githubusercontent.com/1043668/91643909-9c9f2e00-ea37-11ea-8453-a6c5ffca8680.png)

But when I remove `ts-loader` and just use `babel-loader` it works:

![image](https://user-images.githubusercontent.com/1043668/91643921-acb70d80-ea37-11ea-954d-2007d80eb257.png)

It's not even about `babel-loader`. It doesn't work when I just use `ts-loader` with your plugin too. What am I missing? Is my tsconfig wrong?

Can you please help me? Any form of support is appreciated.

## Example Repo

- <https://github.com/natterstefan/loadable-components-example>

**Comment by acrazing** [comment] 2020-08-30 03:45
It's caused by the comments of webpack, and fixed in `typescript-loadable-components-plugin@1.0.1`, you can try it now!

**Closed by acrazing** 2020-08-30 03:45 UTC

**Comment by acrazing** [comment] 2020-08-30 03:47
Thanks for your feedback, you may be the first user of this repository!

**Comment by natterstefan** [comment] 2020-08-30 07:30
Hi @acrazing,

thanks for your fast response. It works now! Awesome.

-----

Looks like you know a lot about loadable components. Can you tell me why I need to specify `'@loadable/component'` as `externals` in the [webpack config](https://github.com/gregberge/loadable-components/blob/8d29fef8f02e5b0cdd4a1add3399e48089a7b97a/examples/server-side-rendering/webpack.config.babel.js#L40) for SSR? Without this, I run into several issues.

(sorry out of scope, we can move to another channel if you want)
